Repository CA-G12/jack-trades, pull requests merged in 2022-11, with the labels that each got.

#118 115 handle request feature
  .vscode/settings.json
  __test__/Request.test.ts
  __test__/Wishlist.test.ts
  client/package-lock.json
  client/package.json
  client/src/components/Button/Button.css
  client/src/components/Button/Button.tsx
  client/src/components/ProductContainer/ProductContainer.css
  client/src/components/ProductContainer/ProductContainer.tsx
  client/src/components/ProductDetails/ProductDetails.tsx
  client/src/interfaces/ButtonPropsTypes.ts
  client/src/interfaces/ProductDetailsInterface.ts
  package-lock.json
  package.json
  server/app.ts
  server/controllers/index.ts
  server/controllers/request/addRequest.ts
  server/controllers/request/index.ts
  server/controllers/wishList/addToWishList.ts
  server/controllers/wishList/checkWishlist.ts
  server/controllers/wishList/deleletFromWishList.ts
  server/controllers/wishList/index.ts
  server/database/queries/Requests/addRequest.ts
  server/database/queries/Requests/checkSelectedQuery.ts
  server/database/queries/Requests/getProuctType.ts
  server/database/queries/Requests/getRequest.ts
  server/database/queries/Requests/index.ts
  server/database/queries/index.ts
  server/database/queries/wishlist/checkInWishList.ts
  server/database/queries/wishlist/index.ts
  server/interfaces/IRequest.ts
  server/interfaces/index.ts
  server/models/requests.ts
  server/routes/request.ts
  server/routes/wishlist.ts
  server/validation/index.ts
  server/validation/requestValidation.ts
  server/validation/validateAddRequest.ts
Labels: Awaiting Review

#107 products page filters [backend] [frontend]
  __test__/products.test.ts
  client/src/components/ProductsCategory/ProductsCategoryCard.tsx
  client/src/components/ProductsCategory/ProductsCategoryList.tsx
  client/src/components/ProductsFilter/ProductsFilter.tsx
  client/src/components/ProductsSearch/ProductsSearch.tsx
  client/src/interfaces/ProductsPageInterfaces.ts
  client/src/interfaces/index.ts
  client/src/pages/ProductsPage.tsx
  server/controllers/index.ts
  server/controllers/products/filterProducts.ts
  server/controllers/products/getAllProducts.ts
  server/controllers/products/getCategories.ts
  server/controllers/products/index.ts
  server/database/queries/products/getAllProducts.ts
  server/database/queries/products/getCategories.ts
  server/database/queries/products/index.ts
  server/interfaces/index.ts
  server/interfaces/productsPage.ts
  server/routes/products.ts
Labels: Awaiting Review

#120 Add test cases for adding product controller
  __test__/products.test.ts
  server/controllers/products/addProduct.ts
  server/validation/newProductValidation.ts
Labels: Awaiting Review

#122 117 create request popup
  client/src/components/Context/ImageContext.tsx
  client/src/components/Image/Image.css
  client/src/components/ImagesList/ImageList.css
  client/src/components/Loading/Loading.css
  client/src/components/ProductContainer/ProductContainer.css
  client/src/components/ProductContainer/ProductContainer.tsx
  client/src/components/ProductDetails/ProductDetails.css
  client/src/components/ProductDetails/ProductDetails.tsx
  client/src/components/ProductImage/ProductImage.css
  client/src/components/ProductImage/ProductImage.tsx
  client/src/components/RequestPopup/Popup.css
  client/src/components/RequestPopup/PopupCard.tsx
  client/src/components/RequestPopup/index.tsx
  client/src/components/UserProducts/index.tsx
  client/src/interfaces/IProduct.ts
  client/src/interfaces/IProductProps.ts
  client/src/interfaces/IProductsPopup.ts
  client/src/interfaces/ImageContext.ts
  client/src/interfaces/ProductDetailsInterface.ts
  client/src/interfaces/index.ts
  server/controllers/request/addRequest.ts
  server/controllers/user/getUserProducts.ts
  server/database/queries/getUserProductsQuery.ts
  server/validation/validateAddRequest.ts
Labels: Approved

#124 123 exchange donation notification
  __test__/Request.test.ts
  server/controllers/index.ts
  server/controllers/notifications/getAllNotification.ts
  server/controllers/request/deleteRequest.ts
  server/controllers/request/getAllOfferedProducts.ts
  server/controllers/request/getAllRequest.ts
  server/controllers/request/index.ts
  server/controllers/request/updateRequest.ts
  server/database/queries/Requests/checkRequest.ts
  server/database/queries/Requests/declineAllOtherRequests.ts
  server/database/queries/Requests/deleteRequestQuery.ts
  server/database/queries/Requests/getAllOfferedDetailsQuery.ts
  server/database/queries/Requests/getAllOfferedProducts.ts
  server/database/queries/Requests/getAllRequests.ts
  server/database/queries/Requests/getIsExchangeableQuery.ts
  server/database/queries/Requests/index.ts
  server/database/queries/Requests/updateRequest.ts
  server/database/queries/index.ts
  server/database/queries/notifications/getReceiverNotificationsQuery.ts
  server/database/queries/notifications/getSenderNotifications.ts
  server/database/queries/notifications/index.ts
  server/interfaces/models.ts
  server/models/index.ts
  server/models/requests.ts
  server/routes/notifications.ts
  server/routes/request.ts
  server/validation/index.ts
  server/validation/updateRequest.ts
Labels: Approved

#127 126 create wishlist component
  __test__/Wishlist.test.ts
  client/src/StaticData/Links.ts
  client/src/components/Header/Header.css
  client/src/components/NavBar/Navbar.tsx
  client/src/components/ProductDetails/ProductDetails.css
  client/src/components/ProductDetails/ProductDetails.tsx
  client/src/components/Wishlist/Wishlist.css
  client/src/components/Wishlist/WishlistCard.tsx
  client/src/components/Wishlist/index.tsx
  client/src/interfaces/IWishlistItem.ts
  client/src/interfaces/index.ts
  client/src/pages/ProductDetails.tsx
  client/src/pages/ProductsPage.tsx
  server/controllers/wishList/getAllWishlistItems.ts
  server/database/queries/wishlist/getAllWishListItemsQuery.ts
Labels: Approved

#131 14 products page getallproducts
  __test__/products.test.ts
  client/src/components/CategoriesSlider/index.tsx
  client/src/components/ImagesList/ImagesList.tsx
  client/src/components/Introduction/index.tsx
  client/src/components/ProductsSearch/ProductsSearch.css
  client/src/components/ProductsSearch/ProductsSearch.tsx
  server/controllers/products/filterProducts.ts
  server/database/fakeData.ts
Labels: Approved

#128 Created Requests Component >> profile page
  __test__/Request.test.ts
  client/package-lock.json
  client/package.json
  client/src/components/Requests/UserRequest.css
  client/src/components/Requests/UserRequest.tsx
  client/src/components/Requests/index.tsx
  client/src/interfaces/IUserRequest.ts
  client/src/interfaces/index.ts
  package-lock.json
  package.json
  server/controllers/notifications/getAllNotification.ts
  server/controllers/request/deleteRequest.ts
  server/controllers/request/getAllRequest.ts
  server/controllers/request/updateRequest.ts
  server/database/queries/Requests/getAllRequests.ts
Labels: Approved

#133 132 io
  __test__/Request.test.ts
  __test__/Wishlist.test.ts
  __test__/account.test.ts
  __test__/products.test.ts
  __test__/user.test.ts
  __test__/website.test.ts
  client/package-lock.json
  client/package.json
  client/src/components/Context/AuthContext.tsx
  client/src/components/Context/ImageContext.tsx
  client/src/components/NavBar/Navbar.tsx
  client/src/components/ProductDetails/ProductDetails.tsx
  client/src/components/RequestPopup/index.tsx
  client/src/interfaces/IAuthContextProps.ts
  client/src/interfaces/IProductsPopup.ts
  client/src/interfaces/ImageContext.ts
  server/IOHandler/IoHandler.ts
  server/app.ts
  server/controllers/account/checkAuth.ts
  server/database/queries/account/getNameQuery.ts
  server/database/queries/account/index.ts
  server/database/queries/index.ts
  server/index.ts
Labels: Awaiting Review

#135 handled chat feature
  server/controllers/chat/addMessage.ts
  server/controllers/chat/getAllMessages.ts
  server/controllers/chat/index.ts
  server/controllers/index.ts
  server/database/queries/chat/addMessage.ts
  server/database/queries/chat/getAllMessageQuery.ts
  server/database/queries/chat/index.ts
  server/database/queries/getUserProductsQuery.ts
  server/database/queries/index.ts
  server/interfaces/index.ts
  server/interfaces/models.ts
  server/models/Chat.ts
  server/models/index.ts
  server/routes/chat.ts
  server/routes/index.ts
  server/validation/chatValidation.ts
  server/validation/index.ts
Labels: Approved

#138 modified the profile page
  __test__/Wishlist.test.ts
  client/src/components/NoData/NoData.css
  client/src/components/NoData/index.tsx
  client/src/components/ProductDetails/ProductDetails.css
  client/src/components/Requests/UserRequest.css
  client/src/components/Requests/index.tsx
  client/src/components/SignupForm/SignupForm.tsx
  client/src/components/UserInfo/UserInfo.css
  client/src/components/UserInfo/index.tsx
  client/src/components/UserProducts/UserProductCard.tsx
  client/src/components/UserProducts/index.tsx
  client/src/components/Wishlist/Wishlist.css
  client/src/components/Wishlist/index.tsx
  client/src/pages/ProfilePage.tsx
  server/controllers/wishList/getAllWishlistItems.ts
Labels: Awaiting Review

#140 13 feedback post
  client/package-lock.json
  client/public/index.html
  client/src/pages/AboutPage.tsx
  package.json
  server/controllers/website/addFeedback.ts
  server/controllers/website/getFeedback.ts
  server/database/queries/index.ts
  server/database/queries/website/addFeedback.ts
  server/database/queries/website/getFeedback.ts
  server/routes/website.ts
Labels: Awaiting Review

#142 141 io chat
  __test__/account.test.ts
  client/src/components/Chat/index.tsx
  client/src/components/Chat/style.css
  client/src/components/Context/AuthContext.tsx
  client/src/components/NavBar/Navbar.tsx
  client/src/components/UserInfo/UserInfo.css
  client/src/components/UserInfo/index.tsx
  client/src/interfaces/IAllMessages.ts
  client/src/interfaces/IAuthContextProps.ts
  client/src/interfaces/IChatData.ts
  client/src/interfaces/index.ts
  client/src/pages/ProfilePage.tsx
  server/IOHandler/IoHandler.ts
  server/controllers/account/checkAuth.ts
  server/controllers/chat/addMessage.ts
  server/controllers/chat/getAllMessages.ts
  server/controllers/chat/getUnseenMessagse.ts
  server/controllers/chat/index.ts
  server/controllers/chat/updateUnSeenMessages.ts
  server/controllers/index.ts
  server/database/queries/account/getNameQuery.ts
  server/database/queries/chat/getAllUnseenMessages.ts
  server/database/queries/chat/index.ts
  server/database/queries/chat/updateUnseenMessages.ts
  server/database/queries/index.ts
  server/interfaces/models.ts
  server/models/Chat.ts
  server/routes/chat.ts
Labels: Awaiting Review

#144 fix bug
  client/src/components/NavBar/Navbar.tsx
Labels: Approved

#148 change the localhost:3000 from the app file to env
  server/app.ts
Labels: Awaiting Review

#146 added the unseen notifications feature
  client/src/components/NavBar/Navbar.tsx
  client/src/components/NotificationContainer/NotificationContainer.tsx
  server/controllers/index.ts
  server/controllers/notifications/getUnseenNotifications.ts
  server/controllers/notifications/index.ts
  server/controllers/notifications/updateNotifications.ts
  server/database/queries/index.ts
  server/database/queries/notifications/getUnseenReceiverNotifications.ts
  server/database/queries/notifications/getUnseenSenderNotifications.ts
  server/database/queries/notifications/index.ts
  server/database/queries/notifications/updateReceiverNotifications.ts
  server/database/queries/notifications/updateSenderNotificaions.ts
  server/interfaces/models.ts
  server/models/requests.ts
  server/routes/notifications.ts
Labels: Awaiting Review

#149 145 real time notification
  client/src/components/Context/ImageContext.tsx
  client/src/components/NavBar/Navbar.tsx
  client/src/components/NotificationCard/NotificationCard.tsx
  client/src/components/NotificationCard/NotificationPopUp.tsx
  client/src/components/NotificationContainer/NotificationContainer.tsx
  client/src/interfaces/IProductsPopup.ts
  server/IOHandler/IoHandler.ts
Labels: Awaiting Review

#151 add the add feeback putton to the feedback page
  client/src/pages/AboutPage.tsx
Labels: Awaiting Review

#154 refactor code
  __test__/account.test.ts
  client/src/assets/google.png
  client/src/components/AddProduct/index.tsx
  client/src/components/Context/ImageContext.tsx
  client/src/components/NavBar/Navbar.tsx
  client/src/components/NotificationCard/NotificationCard.tsx
  client/src/components/ProductDetails/ProductDetails.tsx
  client/src/components/ProductsCategory/ProductsCategoryCard.tsx
  client/src/components/SignupForm/SignupForm.css
  client/src/components/SignupForm/SignupForm.tsx
  client/src/components/Statistics/Statistics.tsx
  client/src/pages/ProfilePage.tsx
  server/IOHandler/IoHandler.ts
  server/app.ts
  server/controllers/account/signIn.ts
  server/controllers/chat/addMessage.ts
  server/controllers/request/updateRequest.ts
  server/controllers/website/getStatistics.ts
  server/database/queries/index.ts
  server/database/queries/wishlist/deleteProductFromAllWishList.ts
  server/database/queries/wishlist/index.ts
  server/middlewares/authentication.ts
  server/validation/signinValidation.ts
Labels: Approved

#158 handle un157-Unauthorized-product-details
  client/src/components/Chat/index.tsx
  client/src/components/ProductDetails/ProductDetails.tsx
Labels: Approved

#163 162-edit-nav
  client/src/StaticData/Links.ts
  client/src/components/NavBar/Navbar.tsx
Labels: Awaiting Review

#164 modified landing page
  client/src/components/CategoriesSlider/CategoriesSlider.css
  client/src/components/CategoriesSlider/index.tsx
  client/src/components/Header/Header.css
  client/src/components/Header/Header.tsx
  client/src/components/Introduction/Introduction.css
  client/src/components/Introduction/index.tsx
  client/src/components/Statistics/Statistics.css
  client/src/components/Statistics/Statistics.tsx
Labels: Awaiting Review

#167 fixed sign up form
  client/src/components/AccountIntro/AccountIntro.css
  client/src/components/SignupForm/SignupForm.css
  client/src/components/SignupForm/SignupForm.tsx
Labels: Approved

#168 prevented the page from refetchin in every operation
  client/src/components/NavBar/Navbar.tsx
  client/src/components/NotificationCard/NotificationCard.tsx
  client/src/components/NotificationCard/NotificationPopUp.tsx
  client/src/components/NotificationContainer/NotificationContainer.tsx
  client/src/interfaces/IProductsPopup.ts
Labels: Approved

#171 added the required for add feedback!
  client/src/pages/AboutPage.tsx
Labels: Approved

#172 Refactor product details
  client/src/components/Context/ImageContext.tsx
  client/src/components/NotificationCard/NotificationCard.css
  client/src/components/NotificationCard/NotificationCard.tsx
  client/src/components/NotificationCard/PopupCard.tsx
  client/src/components/ProductDetails/ProductDetails.tsx
  client/src/components/RequestPopup/Popup.css
  client/src/components/RequestPopup/PopupCard.tsx
  client/src/components/RequestPopup/index.tsx
  client/src/components/UserInfo/index.tsx
Labels: Awaiting Review

#174 fixed images in the chat and added base url to react app, also integr…
  client/.env.exanple
  client/.gitignore
  client/src/components/Chat/index.tsx
  client/src/components/Context/AuthContext.tsx
  client/src/components/Context/index.ts
  client/src/components/NavBar/Navbar.tsx
Labels: Awaiting Review

#176 update user profile
  server/controllers/index.ts
  server/controllers/user/index.ts
  server/controllers/user/updateUserProfile.ts
  server/database/queries/index.ts
  server/database/queries/products/index.ts
  server/database/queries/user/index.ts
  server/database/queries/user/updateUserProfileQuery.ts
  server/routes/users.ts
  server/validation/index.ts
  server/validation/updateUserProfileValidation.ts
Labels: Awaiting Review

#182 modified auth route, and fixed the z-index of the swal alert
  __test__/account.test.ts
  client/src/components/Context/AuthContext.tsx
  client/src/components/NotificationCard/NotificationCard.css
  client/src/components/NotificationContainer/notificationContainer.css
  client/src/components/ProductDetails/ProductDetails.css
  client/src/components/ProductDetails/ProductDetails.tsx
  client/src/components/ProductImage/ProductImage.css
  client/src/components/RequestPopup/Popup.css
  server/controllers/account/checkAuth.ts
  server/database/queries/account/getNameQuery.ts
  server/routes/account.ts
Labels: Awaiting Review

#184 177 react user profile
  __test__/user.test.ts
  client/package-lock.json
  client/package.json
  client/src/components/UserInfo/index.tsx
  client/src/components/index.ts
  client/src/components/userProfilePopup/popup.css
  client/src/components/userProfilePopup/popup.tsx
  client/src/interfaces/IProfilePopupProps.ts
  client/src/interfaces/UserInfoProps.ts
  client/src/interfaces/index.ts
  client/src/pages/ProfilePage.tsx
  client/src/validation/index.ts
  client/src/validation/newProductValidation.ts
  client/src/validation/updateUserValidation.ts
  server/controllers/user/updateUserProfile.ts
  server/database/queries/index.ts
  server/database/queries/user/checkEmailQuery.ts
  server/database/queries/user/getUserProfile.ts
  server/database/queries/user/index.ts
  server/database/queries/user/updateUserProfileQuery.ts
  server/validation/updateUserProfileValidation.ts
Labels: Approved

#187 186 add formik
  client/src/components/AccountIntro/AccountIntro.css
  client/src/components/AddProduct/AddProduct.css
  client/src/components/AddProduct/CategoryRadio.tsx
  client/src/components/AddProduct/TypeRadio.tsx
  client/src/components/AddProduct/index.tsx
  client/src/components/NotificationContainer/notificationContainer.css
  client/src/components/ProductDetails/ProductDetails.css
  client/src/components/Signin/Signin.css
  client/src/components/Signin/Signin.tsx
  client/src/components/SignupForm/SignupForm.css
  client/src/interfaces/ICategoryRadioProps.ts
  client/src/interfaces/IFormik.ts
  client/src/interfaces/IImages.ts
  client/src/interfaces/ITypeRadioProps.ts
  client/src/interfaces/index.ts
  client/src/validation/newProductValidation.ts
Labels: Awaiting Review

#188 added state to profile link, so when the user clicks on the profile l…
  client/src/components/NotificationCard/NotificationCard.tsx
  client/src/pages/ProfilePage.tsx
Labels: Done
